services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${SERVER_CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT_INTERNAL}"
    volumes:
      - "./app:/code/app"
    environment:
      ENV: "dev"
    networks:
      - monolith

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "${CACHE_NAME}"
    networks:
      - monolith
    depends_on:
      - server

networks:
  monolith:
    driver: bridge