services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT_INTERNAL}"
    volumes:
      - "./app:/code/app"
      - "./db:/code/db"
      - "./app/src/domain:/code/domain"
    environment:
      ENV: "dev"
    networks:
      - backend
networks:
  backend:
    driver: bridge