services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${SERVER_CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT_INTERNAL}"
    volumes:
      - "./app:/code/app"
      - "./alembic:/code/alembic"
      - "./code/app/src/domain:/code/domain"
    environment:
      ENV: "dev"
    networks:
      - backend
networks:
  monolith:
    driver: bridge