services:
  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile"
    container_name: "${SERVER_CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT_INTERNAL}"
    volumes:
      - "./server/src:/code/src"
      - "./server/test:/code/test"
      - "./server/main.py:/code/main.py"
    environment:
      ENV: "dev"
      HOST_PORT: "${SERVER_PORT}"
    networks:
      - monolith

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: "${CACHE_NAME}"
    networks:
      - monolith
    depends_on:
      - server

networks:
  monolith:
    driver: bridge